MTOW = loadFields(SP,'Weight.MTOW')
minPax=loadFields(SP,'Payload.paxMin')
maxPax=loadFields(SP,'Payload.paxMax')
crew=loadFields(SP,'Payload.crew')
range=loadFields(SP,'Actuations.Range')
MPL=loadFields(SP,'Weight.MPL')
OEW=loadFields(SP,'Weight.OEW')
EW=loadFields(SP,'Weight.EW')